### ISSUE TITLE
Strange interaction with C-c C-u C-u

### ISSUE THREAD

**Issue by ivanperez-keera** [yjwen/org-reveal#295] opened 2017-09-18 12:44 UTC
I have `C-c C-u C-u` bound to a function.

The export function fails.

Is anyone else experiencing this?

**Comment by yjwen** [comment] 2019-07-14 16:30
Tried to bind `C-c C-u C-u` to `compile` and my org file export succeeded. Cannot reproduce the issue. Close the issue for now. If the issue still exists, please reopen it.

**Closed by yjwen** 2019-07-14 16:30 UTC
