### ISSUE TITLE
bug: XML comment not escaped

### ISSUE THREAD

**Issue by VladimirAlexiev** [yjwen/org-reveal#95] opened 2015-02-08 13:45 UTC
If there is a XML comment in an EXAMPLE block or ":"-formatted block, e.g.:
```
: {{TemplateMapping | mapToClass = 
: | mappings = 
: 	<!-- {{ PropertyMapping | templateProperty = imdb | ontologyProperty = }} -->
: 	<!-- {{ PropertyMapping | templateProperty = Име | ontologyProperty = }} -->
```
then the XML comment lines do not appear.

Looks like more escaping is required.

html-export doesn't have thsi problem, so why does reveal have it? In general: the more you use from html-export "as is", the better

**Comment by yjwen** [comment] 2015-02-09 15:07
Hi,

I tried with the latest org-reveal and the comment lines are there.

![linux](https://cloud.githubusercontent.com/assets/4273142/6108672/0472a84e-b0b0-11e4-9c44-9e8671cec78e.png)

org-reveal is using ox-html's function for exporting EXAMPLE blocks.

It is strange, but anyway, could you please pull the latest codes and try again?
If the comment lines are still missing, then could you please provide an example org file to show the issue?

**Comment by yjwen** [comment] 2015-02-24 16:17
Hi,

  I am closing this issue because it cannot be reproduced. Should you have any further consideration, please feel free to re-open it.

Yujie

**Closed by yjwen** 2015-02-24 16:17 UTC

**Comment by VladimirAlexiev** [comment] 2015-03-21 11:24
Sorry for misleading you. I still haven't had time to upgrade reveal.js (I have some custom settings in reveal styles), if I discover something I'll write. Thanks!
