### ISSUE TITLE
Org easy templates expansion not working when using ox-reveal

### ISSUE THREAD

**Issue by ZzAntares** [yjwen/org-reveal#323] opened 2018-03-19 02:23 UTC
Hello, I'm experiencing a weird issue when using this package. This is a minimal `org` related config that I'm using:

```elisp
(use-package org)

(use-package org-tempo
  :after org
  :demand t
  :straight nil)

(use-package org-bullets
  :after org
  :demand t
  :config
  (org-bullets-mode 1))

(use-package ox-gfm
  :after org
  :demand t)

(use-package ox-reveal
  :after org
  :demand t
  :config
  (setq org-reveal-root "https://cdn.jsdelivr.net/npm/reveal.js@3.6.0"
        org-reveal-mathjax t))
```

With this config when in `org` buffers expanding easy templates does not work (i.e. `<s` + `TAB` does nothing), however when I remove `ox-reveal` my easy template expansion works like a charm!

I'm using `org 9.1.7` installed via `straight.el`.

So in short... using `ox-reveal` disables org easy templates expansion, but why?

**Comment by Jean-MichelC** [comment] 2018-05-21 20:15
Same issue here: below my work-around.
My `org-version` is `9.1.13`.
I think the issue is due to the following in ox-reveal.el:
```;; Register auto-completion for speaker notes.
(when org-reveal-note-key-char
  (add-to-list 'org-structure-template-alist
               (list org-reveal-note-key-char "#+BEGIN_NOTES\n\?\n#+END_NOTES")))
```

As I understand, this works with org 8 but not org 9.
I have the following work-around (requires dash.el, but very easy to convert into plain old elisp):
```      
(->> org-structure-template-alist
     (cdr) ;; the last value is added by ox-reveal and is set up the old way
     (cons `(,org-reveal-note-key-char . "notes")) ;; the new way
     (setq org-structure-template-alist))
```
Tested, works.

Or if you prefer, change directly the last bunch of code in ox-reveal.el:
```;; Register auto-completion for speaker notes.
(when org-reveal-note-key-char
  (add-to-list 'org-structure-template-alist
               (list org-reveal-note-key-char "#+BEGIN_NOTES\n\?\n#+END_NOTES")))
```
into
```;; Register auto-completion for speaker notes.
(when org-reveal-note-key-char
  (add-to-list 'org-structure-template-alist (cons `(,org-reveal-note-key-char . "notes")))
```
Not tested though.

**Comment by tohojo** [comment] 2018-10-17 12:59
There's a cons too much; in that example, but can confirm that this works for me:

```
(when org-reveal-note-key-char
  (add-to-list 'org-structure-template-alist `(,org-reveal-note-key-char . "notes")))
```

**Comment by yjwen** [comment] 2019-07-10 16:07
Already merged.

**Closed by yjwen** 2019-07-10 16:07 UTC
