### ISSUE TITLE
Translate «Table of contents» in document language

### ISSUE THREAD

**Issue by nonglobal** [yjwen/org-reveal#454] opened 2021-09-28 14:39 UTC
If I define 
#+LANGUAGE: es
#+OPTIONS: toc:t

The Title of the TOC is rendered in english: "Table of Contents" in the reveal presentation.
On the contrary, with de same config export org>html ando org>LaTeX the Title of TOC is rendered correctly: «Table de Matièrers» or «índice» (french and spanish, for example)
Is there any mode to customize the title in the apropriate language of document?
Thanks in advance.

**Comment by yjwen** [comment] 2021-10-01 08:59
My local test shows TOC was rendered correctly to Spanish. Here is the minimum org I was using.
```
#+LANGUAGE: es
#+OPTIONS: toc:t
* Heading 1
* Heading 2
```
And here is the TOC part of the exported reveal.js.
```html
<h2>&Iacute;ndice</h2>
<div id="text-table-of-contents">
<ul>
<li><a href="#/slide-org18e7a72">1. Heading 1</a></li>
<li><a href="#/slide-org6619ad3">2. Heading 2</a></li>
</ul>
```

Could you please provide a minimal example org file that can reproduce the error?

**Comment by nonglobal** [comment] 2021-10-04 13:20
Using the same minimal org elements as you I get this:

</section>
<section id="table-of-contents-section">
<div id="table-of-contents">
<h2>Table of Contents</h2>
<div id="text-table-of-contents">
<ul>
<li><a href="#/slide-1">1. Heading 1</a></li>
<li><a href="#/slide-2">2. Heading 2</a></li>
</ul>
</div>
</div>
</section>

**Comment by nonglobal** [comment] 2021-10-04 13:24
Using the same minimal org file as you I get:

```
</section>
<section id="table-of-contents-section">
<div id="table-of-contents">
<h2>Table of Contents</h2>
<div id="text-table-of-contents">
<ul>
<li><a href="#/slide-1">1. Heading 1</a></li>
<li><a href="#/slide-2">2. Heading 2</a></li>
</ul>
</div>
</div>
</section>
```

**Comment by yjwen** [comment] 2021-10-05 14:14
The exported HTML does not looks like generated by org-reveal. Are you using org-re-reveal? 




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yjwen/org-reveal"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月4日(星期一) 晚上9:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yjwen/org-reveal] Translate «Table of contents» in document language (#454)





 
Using the same minimal org file as you I get:
 </section&gt; <section id="table-of-contents-section"&gt; <div id="table-of-contents"&gt; <h2&gt;Table of Contents</h2&gt; <div id="text-table-of-contents"&gt; <ul&gt; <li&gt;<a href="#/slide-1"&gt;1. Heading 1</a&gt;</li&gt; <li&gt;<a href="#/slide-2"&gt;2. Heading 2</a&gt;</li&gt; </ul&gt; </div&gt; </div&gt; </section&gt;  
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lechten** [comment] 2021-10-05 16:10
Indeed, I just fixed this in org-re-reveal 3.12.0.

**Comment by yjwen** [comment] 2021-10-10 03:58
I see. It must be a org-re-reveal issue and has been fixed. Close this issue.

**Closed by yjwen** 2021-10-10 03:58 UTC

**Comment by yjwen** [comment] 2021-10-22 04:15
@nonglobal Sorry to hear that. Hope everything is going well now.
