### ISSUE TITLE
Fragments need 2 keypresses for transitions

### ISSUE THREAD

**Issue by knl** [yjwen/org-reveal#143] opened 2015-09-10 12:09 UTC
If I try using fragments, I need 2 keypresses for each transition.

For the 'Thanks' slide of this project's `Readme.org`, I get the following output:

``` html
<section id="slide-orgheadline11">
<h2 id="orgheadline11">Thanks</h2>
<p>
Courtesy to:
</p>

<span class="fragment roll-in"><p class="fragment roll-in">
The powerful Org-mode,
</p></span>
<span class="fragment roll-in"><p class="fragment roll-in">
the impressive Reveal.js
</p></span>
<span class="fragment roll-in"><p class="fragment roll-in">
and the precise MathJax
</p></span>
```

Which seems to point to the problem, there are both `span` and `p` that both have `fragment` and `roll-in` class attribute.

**Comment by yjwen** [comment] 2015-09-15 08:00
The issue is in stable branch. When I was merging master to stable, the new fragment code is merged while the old fragment specification by `<span>` wrapping is still there, cause double-fragments.

Has been fixed in stable branch. Please wait for MELPA's update.

**Closed by yjwen** 2015-09-15 08:00 UTC

**Comment by knl** [comment] 2015-09-15 08:18
Hi Yujie, thanks! Will wait for the MELPA's update, but I think I'll switch to using the master branch. Thanks for this wonderful project, it is making my work-life really pleasant.

**Comment by yjwen** [comment] 2015-09-15 08:25
You are welcome. I am glad to know org-reveal helps. :)

2015-09-15 16:18 GMT+08:00 Nikola Knežević <notifications@github.com>:
